name: truth_box
description: trying my first app with very good cli its and experimental project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  shared_preferences: ^2.5.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf

  assets:
    - assets/icons/
    
        
